services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: startup_validator
    volumes:
      - volume-data:/var/lib/postgresql/data
    networks:
      - my-network

volumes:
  volume-data:

networks:
  my-network:
